application: dlsaa-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0

handlers:
- url: /static
  static_dir: static

# Endpoints handler
- url: /_ah/spi/.*
  script: services.application

# Management front-end
- url: /.*
  script: dlsaa.application
